/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'rgb(var(--bg) / <alpha-value>)',
        panel: 'rgb(var(--panel) / <alpha-value>)',
        panelAlt: 'rgb(var(--panel-alt) / <alpha-value>)',
        panelHover: 'rgb(var(--panel-hover) / <alpha-value>)',
        text: 'rgb(var(--text) / <alpha-value>)',
        textSecondary: 'rgb(var(--text-secondary) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        line: 'rgb(var(--line) / <alpha-value>)',
        lineSubtle: 'rgb(var(--line-subtle) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        accentMid: 'rgb(var(--accent-mid) / <alpha-value>)',
        accentSoft: 'rgb(var(--accent-soft) / <alpha-value>)',
        accentMuted: 'rgb(var(--accent-muted) / <alpha-value>)',
        success: 'rgb(var(--success) / <alpha-value>)',
        successBg: 'rgb(var(--success-bg) / <alpha-value>)',
        warning: 'rgb(var(--warning) / <alpha-value>)',
        warningBg: 'rgb(var(--warning-bg) / <alpha-value>)',
        danger: 'rgb(var(--danger) / <alpha-value>)',
        dangerBg: 'rgb(var(--danger-bg) / <alpha-value>)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        soft: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
      },
      borderRadius: {
        DEFAULT: '6px',
        sm: '4px',
        md: '8px',
        lg: '10px',
        xl: '12px',
        '2xl': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['11px', '16px'],
        xs: ['12px', '18px'],
        sm: ['13px', '20px'],
        base: ['14px', '22px'],
        md: ['15px', '24px'],
        lg: ['16px', '26px'],
        xl: ['18px', '28px'],
        '2xl': ['20px', '30px'],
        '3xl': ['24px', '32px'],
        '4xl': ['30px', '38px'],
      },
      spacing: {
        sidebar: 'var(--sidebar-w)',
        topbar: 'var(--topbar-h)',
      },
    },
  },
  plugins: [],
};
