import { CampaignTabs } from '@/components/tabs';
import { Badge, Card, EmptyState } from '@/components/ui';
import { getCampaignRecommendations } from '@/lib/api';
import type { CampaignRecommendation } from '@/types/api';

export const metadata = {
  title: 'Insights',
};

const PRIORITY_ORDER: Record<string, number> = { high: 0, medium: 1, low: 2 };

function getPriorityTone(priority: string): 'warning' | 'neutral' | 'success' {
  if (priority === 'high') return 'warning';
  if (priority === 'medium') return 'neutral';
  return 'success';
}

export default async function CampaignRecommendationsPage({
  params,
}: Readonly<{ params: { id: string } }>) {
  const campaignId = Number(params.id);
  const recommendations = await getCampaignRecommendations(campaignId).catch(
    () => [] as CampaignRecommendation[],
  );

  // Group by priority
  const sorted = [...recommendations].sort(
    (a, b) => (PRIORITY_ORDER[a.priority] ?? 9) - (PRIORITY_ORDER[b.priority] ?? 9),
  );

  const grouped = sorted.reduce<Record<string, CampaignRecommendation[]>>((acc, rec) => {
    const key = rec.priority.toLowerCase();
    if (!acc[key]) acc[key] = [];
    acc[key].push(rec);
    return acc;
  }, {});

  const priorityGroups = ['high', 'medium', 'low'].filter((p) => grouped[p]?.length > 0);

  return (
    <div className="mx-auto max-w-5xl px-6 py-8">
      <CampaignTabs campaignId={campaignId} activeTab="recommendations" />

      {recommendations.length === 0 ? (
        <EmptyState
          title="No insights yet"
          description="Generate the campaign to produce optimization insights."
        />
      ) : (
        <div className="space-y-8">
          {/* Header context */}
          <div className="flex items-center gap-4 rounded-lg border border-line bg-panel px-4 py-3">
            <div className="flex-1 text-xs text-muted leading-relaxed">
              These insights are generated by the optimization workflow based on campaign structure and analytics patterns.
              <span className="ml-1 font-medium text-text">Evidence</span> reflects data from the analytics engine.{' '}
              <span className="font-medium text-text">Recommendations</span> are strategic interpretations.
            </div>
            <div className="flex flex-shrink-0 items-center gap-1.5">
              <span className="text-2xs font-semibold uppercase tracking-wide text-muted">
                {recommendations.length} insight{recommendations.length !== 1 ? 's' : ''}
              </span>
            </div>
          </div>

          {priorityGroups.map((priority) => (
            <div key={priority}>
              {/* Group header */}
              <div className="mb-4 flex items-center gap-3">
                <Badge tone={getPriorityTone(priority)}>
                  {priority.toUpperCase()} PRIORITY
                </Badge>
                <div className="h-px flex-1 bg-line" />
                <span className="text-xs text-muted">{grouped[priority].length}</span>
              </div>

              {/* Recommendations in this group */}
              <div className="space-y-4">
                {grouped[priority].map((rec) => (
                  <RecommendationCard key={rec.id} rec={rec} />
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function RecommendationCard({ rec }: { rec: CampaignRecommendation }) {
  return (
    <Card>
      <div className="space-y-4">
        {/* Header */}
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-2xs font-semibold uppercase tracking-widest text-muted">
                {rec.category}
              </span>
            </div>
            <h3 className="text-base font-semibold text-text leading-snug">{rec.title}</h3>
          </div>
          <Badge tone={getPriorityTone(rec.priority)}>{rec.priority}</Badge>
        </div>

        {/* Description */}
        <p className="text-sm leading-relaxed text-textSecondary">{rec.description}</p>

        {/* Evidence (reason) */}
        {rec.reason && (
          <div className="rounded-lg bg-panelAlt px-4 py-3">
            <div className="mb-1 text-2xs font-semibold uppercase tracking-widest text-muted">
              Evidence
            </div>
            <p className="text-xs leading-relaxed text-textSecondary">{rec.reason}</p>
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center gap-2 pt-1">
          <div className="h-1 w-1 rounded-full bg-line" />
          <span className="text-2xs text-muted">
            Measured from campaign analytics · Optimization workflow
          </span>
        </div>
      </div>
    </Card>
  );
}
